import type { Metadata } from "next";

import { Inter } from "next/font/google";
import '@radix-ui/themes/styles.css';
import "./globals.css";

import { Theme, ThemePanel } from '@radix-ui/themes';
import ApiContainer from "@/modules/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  ApiContainer.cradle.user.ep.findMany().then((res) => {
    console.log('res :>> ', res);
  });

  return (
    <html lang="en" style={{ minHeight: '100vh' }}>
      <body className={inter.className}>
        <Theme
          accentColor="blue"
          appearance="dark"
        >
          {children}
          <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}
